version: "3"

services: 
  mqtt: 
    image: eclipse-mosquitto
    labels: 
      - "traefik.enable=true"
      # - "traefik.http.routers.mqtt.entrypoints=web"
      - traefik.tcp.routers.mqtt.rule=HostSNI("ihomemqtt.duckdns.org")
      - traefik.tcp.services.ihomeback.loadbalancer.server.port=1883

  
  grafana:
    image: grafana/grafana
    labels: 
      - "traefik.enable=true"
      # - "traefik.http.routers.grafana.entrypoints=web"
      - traefik.http.routers.grafana.rule=Host("ihomegrafana.duckdns.org")
      - traefik.http.services.ihomeback.loadbalancer.server.port=8080
  
  influx:
    image: influxdb

  datahandler:
    build:
      context: ./datahandler
      dockerfile: ./Dockerfile
    depends_on: 
      - influx
      - mqtt
  
  ihomeback:
    build:
      context: ./ihomeback
      dockerfile: ./Dockerfile
    labels: 
      - "traefik.enable=true"
      # - "traefik.http.routers.mqtt.entrypoints=web"
      - traefik.http.routers.ihomeback.rule=Host("ihomev.duckdns.org")
      - traefik.http.services.ihomeback.loadbalancer.server.port=80
    depends_on: 
      - influx
      - mqtt
  
  traefik:
    image: traefik
    command: 
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports: 
      - 80:80
      - 8080:8080
      # - 1883:8081
  
  
    
    
