version: "3"

services: 
  mqtt: 
    image: eclipse-mosquitto
    volumes: 
      - ./data/mqtt/config:/mosquitto/config
      - ./data/mqtt/data:/mosquitto/data
      - ./data/mqtt/logs:/mosquitto/log
    ports: 
      - 1883:1883
  
  grafana:
    image: grafana/grafana
    volumes: 
      -./data/grafana:/var/lib/grafana
    ports: 
      - 80:3000
  
  influx:
    image: influxdb
    volumes: 
      - ./data/infuxdb:/var/lib/influxdb
    ports: 
      - 8086:8086

  datahandler:
    build:
      context: ./datahandler
      dockerfile: ./Dockerfile
    depends_on: 
      - influx
      - mqtt
  
  ihomeback:
    build:
      context: ./ihomeback
      dockerfile: ./Dockerfile
    depends_on: 
      - influx
      - mqtt
    ports: 
      - 8080:80
  
    
    
